"use client";

import * as React from "react";
import { Sparkles } from "lucide-react";
import { api, ApiError } from "@/lib/api";
import type { AIInsights, AIStatus } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export function AIInsightsCard() {
  const [status, setStatus] = React.useState<AIStatus | null>(null);
  const [result, setResult] = React.useState<AIInsights | null>(null);
  const [busy, setBusy] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);

  React.useEffect(() => {
    (async () => {
      try {
        setStatus(await api.ai.status());
      } catch {
        setStatus(null);
      }
    })();
  }, []);

  async function generate() {
    setBusy(true);
    setError(null);
    try {
      setResult(await api.ai.generateInsights());
    } catch (err) {
      setError(
        err instanceof ApiError
          ? err.status === 503
            ? "AI insights are not configured. Set GROQ_API_KEY on the backend to enable."
            : err.message
          : "Could not generate insights.",
      );
    } finally {
      setBusy(false);
    }
  }

  const configured = status?.configured ?? false;

  return (
    <Card>
      <CardHeader className="flex-row items-center justify-between">
        <CardTitle className="flex items-center gap-2">
          <Sparkles className="size-4" /> AI insights
          {status ? (
            <span className="text-xs font-normal text-muted-foreground">
              · {status.provider} · {status.model}
            </span>
          ) : null}
        </CardTitle>
        <Button size="sm" onClick={generate} disabled={busy}>
          <Sparkles /> {busy ? "Thinking…" : "Generate"}
        </Button>
      </CardHeader>
      <CardContent>
        {!configured && !result ? (
          <p className="text-sm text-muted-foreground">
            Generate natural-language insights and budget recommendations from
            your campaign analytics. Requires a Groq API key on the backend
            (<code className="text-xs">GROQ_API_KEY</code>).
          </p>
        ) : null}

        {error ? (
          <p className="text-sm text-destructive">{error}</p>
        ) : null}

        {result ? (
          <div className="space-y-5">
            <p className="text-sm leading-relaxed">{result.summary}</p>

            {result.insights.length > 0 ? (
              <div>
                <div className="mb-2 text-xs font-medium text-muted-foreground">
                  Key observations
                </div>
                <ul className="space-y-1.5">
                  {result.insights.map((ins, i) => (
                    <li key={i} className="flex gap-2 text-sm">
                      <span className="text-muted-foreground">•</span>
                      <span>{ins}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ) : null}

            {result.recommendations.length > 0 ? (
              <div className="space-y-3">
                <div className="text-xs font-medium text-muted-foreground">
                  Recommendations
                </div>
                {result.recommendations.map((rec, i) => (
                  <div key={i} className="rounded-lg border p-3">
                    <div className="text-sm font-medium">{rec.question}</div>
                    <div className="mt-1 text-sm text-muted-foreground">
                      {rec.answer}
                    </div>
                  </div>
                ))}
              </div>
            ) : null}

            <p className="text-xs text-muted-foreground">
              Generated by {result.model} · review before acting.
            </p>
          </div>
        ) : null}
      </CardContent>
    </Card>
  );
}
