"""initial schema

Revision ID: 46ae677e0465
Revises: 
Create Date: 2026-06-16 16:07:06.838900

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ae677e0465'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_deleted_at'), 'campaigns', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('influencers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('instagram_username', sa.String(length=255), nullable=True),
    sa.Column('youtube_channel', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('manager_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencers_category'), 'influencers', ['category'], unique=False)
    op.create_index(op.f('ix_influencers_city'), 'influencers', ['city'], unique=False)
    op.create_index(op.f('ix_influencers_deleted_at'), 'influencers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_influencers_name'), 'influencers', ['name'], unique=False)
    op.create_table('campaign_influencers',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('influencer_id', sa.UUID(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('deliverables', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_influencers_campaign_id'), 'campaign_influencers', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_influencers_deleted_at'), 'campaign_influencers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_campaign_influencers_influencer_id'), 'campaign_influencers', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_campaign_influencers_status'), 'campaign_influencers', ['status'], unique=False)
    op.create_table('deliverables',
    sa.Column('campaign_influencer_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_influencer_id'], ['campaign_influencers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverables_campaign_influencer_id'), 'deliverables', ['campaign_influencer_id'], unique=False)
    op.create_index(op.f('ix_deliverables_deleted_at'), 'deliverables', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_deliverables_status'), 'deliverables', ['status'], unique=False)
    op.create_table('insights',
    sa.Column('campaign_influencer_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_influencer_id'], ['campaign_influencers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_campaign_influencer_id'), 'insights', ['campaign_influencer_id'], unique=False)
    op.create_index(op.f('ix_insights_deleted_at'), 'insights', ['deleted_at'], unique=False)
    op.create_table('posts',
    sa.Column('campaign_influencer_id', sa.UUID(), nullable=False),
    sa.Column('deliverable_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_influencer_id'], ['campaign_influencers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_campaign_influencer_id'), 'posts', ['campaign_influencer_id'], unique=False)
    op.create_index(op.f('ix_posts_deleted_at'), 'posts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_posts_deliverable_id'), 'posts', ['deliverable_id'], unique=False)
    op.create_table('metrics',
    sa.Column('campaign_influencer_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_influencer_id'], ['campaign_influencers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_campaign_influencer_id'), 'metrics', ['campaign_influencer_id'], unique=False)
    op.create_index(op.f('ix_metrics_deleted_at'), 'metrics', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_metrics_metric_name'), 'metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_metrics_post_id'), 'metrics', ['post_id'], unique=False)
    op.create_index(op.f('ix_metrics_source'), 'metrics', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_source'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_post_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_metric_name'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_deleted_at'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_campaign_influencer_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_posts_deliverable_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_deleted_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_campaign_influencer_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_insights_deleted_at'), table_name='insights')
    op.drop_index(op.f('ix_insights_campaign_influencer_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_deliverables_status'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_deleted_at'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_campaign_influencer_id'), table_name='deliverables')
    op.drop_table('deliverables')
    op.drop_index(op.f('ix_campaign_influencers_status'), table_name='campaign_influencers')
    op.drop_index(op.f('ix_campaign_influencers_influencer_id'), table_name='campaign_influencers')
    op.drop_index(op.f('ix_campaign_influencers_deleted_at'), table_name='campaign_influencers')
    op.drop_index(op.f('ix_campaign_influencers_campaign_id'), table_name='campaign_influencers')
    op.drop_table('campaign_influencers')
    op.drop_index(op.f('ix_influencers_name'), table_name='influencers')
    op.drop_index(op.f('ix_influencers_deleted_at'), table_name='influencers')
    op.drop_index(op.f('ix_influencers_city'), table_name='influencers')
    op.drop_index(op.f('ix_influencers_category'), table_name='influencers')
    op.drop_table('influencers')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_deleted_at'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
