"""agencies and campaign_influencer.agency_id

Revision ID: 50d29fefb6cf
Revises: dccaf4ae84dd
Create Date: 2026-06-19 16:37:19.587741

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '50d29fefb6cf'
down_revision: str | None = 'dccaf4ae84dd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agencies_deleted_at'), 'agencies', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_agencies_name'), 'agencies', ['name'], unique=False)
    op.add_column('campaign_influencers', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_campaign_influencers_agency_id'), 'campaign_influencers', ['agency_id'], unique=False)
    op.create_foreign_key(None, 'campaign_influencers', 'agencies', ['agency_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaign_influencers', type_='foreignkey')
    op.drop_index(op.f('ix_campaign_influencers_agency_id'), table_name='campaign_influencers')
    op.drop_column('campaign_influencers', 'agency_id')
    op.drop_index(op.f('ix_agencies_name'), table_name='agencies')
    op.drop_index(op.f('ix_agencies_deleted_at'), table_name='agencies')
    op.drop_table('agencies')
    # ### end Alembic commands ###
