"""metric influencer scope

Revision ID: dccaf4ae84dd
Revises: 46ae677e0465
Create Date: 2026-06-16 18:19:31.106611

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dccaf4ae84dd'
down_revision: str | None = '46ae677e0465'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('influencer_id', sa.UUID(), nullable=True))
    op.alter_column('metrics', 'campaign_influencer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_metrics_influencer_id'), 'metrics', ['influencer_id'], unique=False)
    op.create_foreign_key(None, 'metrics', 'influencers', ['influencer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.drop_index(op.f('ix_metrics_influencer_id'), table_name='metrics')
    op.alter_column('metrics', 'campaign_influencer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('metrics', 'influencer_id')
    # ### end Alembic commands ###
